- name: Create front network
  community.docker.docker_network:
    name: front-network
    appends: true

- name: Create back network
  community.docker.docker_network:
    name: back-network
    appends: true

- name: Create database volume
  community.docker.docker_volume:
    name: db-data
